apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: shop_logs
      server: clickhouse
      port: 8123
      username: admin
      tlsSkipVerify: true
    secureJsonData:
      password: "admin123"
    editable: true
    isDefault: true